---
- hosts: all
  sudo: yes
  vars_files:
      - rhel-sub-vars.yml     
  tasks:
    - name: disable all amz rhel repos
      command: /usr/bin/yum-config-manager --disable *
    - name: disable amz yum plugin
      lineinfile: dest=/etc/yum/pluginconf.d/amazon-id.conf regexp='^enabled' line='enabled = 0' state=present
    - name: disable rhui-lb yum plugin
      lineinfile: dest=/etc/yum/pluginconf.d/rhui-lb.conf regexp='^enabled' line='enabled = 0' state=present
    - name: enable product-id yum plugin
      lineinfile: dest=/etc/yum/pluginconf.d/product-id.conf regexp='^enabled' line='enabled = 1' state=present
    - name: enable sub manager yum plugin
      lineinfile: dest=/etc/yum/pluginconf.d/subscription-manager.conf regexp='^enabled' line='enabled = 1' state=present
    - name: add subscription DNS to etc hosts (1)
      lineinfile: dest=/etc/hosts state=present insertafter=EOF line='209.132.183.44   xmlrpc.rhn.redhat.com'
    - name: add subscription DNS to etc hosts (2) 
      lineinfile: dest=/etc/hosts state=present insertafter=EOF line='23.204.148.218   content-xmlrpc.rhn.redhat.com'
    - name: add subscription DNS to etc hosts (3)
      lineinfile: dest=/etc/hosts state=present insertafter=EOF line='209.132.183.49   subscription.rhn.redhat.com'
    - name: add RH docker registry to etc hosts (4)
      lineinfile: dest=/etc/hosts state=present insertafter=EOF line='209.132.182.63   registry.access.redhat.com'
    - name: add jboss.org mvn repository to etc hosts (5)
      lineinfile: dest=/etc/hosts state=present insertafter=EOF line='209.132.182.33   repository.jboss.org'
    - name: subscribe RHN
      redhat_subscription: state=present username='{{ username }}' password='{{ password }}' autosubscribe=true pool='{{ pool_id }}'
    - name: disable all repos by default
      shell: subscription-manager repos --disable="*"
